### ISSUE TITLE
Recursive dependency path change

### ISSUE THREAD

**Issue by igala** [jtanx/lddx#1]
When running the lddx like :

lddx -r -m -f "SomeExecutabe" -c ./

it collects all the dependencies but changes the path of the Framework and not its dependencies that reside in /usr/lib

Is there a way to change them as well?

**Comment by jtanx** [comment]
Hmm, can you give an example?

Maybe `--no-default-ignore` along with `--ignored-file` and/or `--ignore-prefix` might be able to do what you want.

**Comment by igala** [comment]
My task is to use a plugin that is loaded by another app (system). I want the app to load an older version of that plugin (with all its dependencies). 
Let say system A is the older and System B is the newer.
I am not sure what is the best way to do it.
I thinking about running :
lddx -r -m -f "PluginExecutabe" -c ./dep
Then copy ./dep and the executable to the new system B and running it there.
Is that the right way to bring all the "PluginExecutable" dependencies?
 
When zipping the folder created on system A and copying them into system B the files lose the dependency path for some reason.

**Comment by jtanx** [comment]
Not withstanding the legalities of bundling the system libraries, have you tried out the flags I mentioned earlier?
